/**
 * Stable error codes for the admin + mobile API.
 * Constitution Principle III: no English strings cross the API boundary.
 * Adding a code is a same-PR operation across three files:
 *   1. this file
 *   2. admin/src/i18n/error-codes.ar-EG.json
 *   3. admin/src/i18n/error-codes.en-US.json
 */
export const ERROR_CODES = {
  // --- Auth / Session ---
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  MUST_CHANGE_PASSWORD: 'MUST_CHANGE_PASSWORD',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',

  // --- Password policy ---
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',
  PASSWORD_BREACHED: 'PASSWORD_BREACHED',
  PASSWORD_ON_COMMON_LIST: 'PASSWORD_ON_COMMON_LIST',
  PASSWORD_BREACH_CHECK_UNAVAILABLE: 'PASSWORD_BREACH_CHECK_UNAVAILABLE',
  PASSWORD_REUSES_RESET_VALUE: 'PASSWORD_REUSES_RESET_VALUE',

  // --- User management ---
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  CANNOT_SELF_MODIFY: 'CANNOT_SELF_MODIFY',
  SUPER_ADMIN_FLOOR_VIOLATED: 'SUPER_ADMIN_FLOOR_VIOLATED',

  // --- Bank programs (feature 002) ---
  BANK_PROGRAM_NOT_FOUND: 'BANK_PROGRAM_NOT_FOUND',
  PROGRAM_CODE_ALREADY_IN_USE: 'PROGRAM_CODE_ALREADY_IN_USE',
  INVALID_VARIABLE_RATE_CONFIGURATION: 'INVALID_VARIABLE_RATE_CONFIGURATION',
  INVALID_QUALITATIVE_REVIEW_CEILING: 'INVALID_QUALITATIVE_REVIEW_CEILING',
  QUALITATIVE_REVIEW_CEILING_BELOW_BASE: 'QUALITATIVE_REVIEW_CEILING_BELOW_BASE',
  DERIVATION_ARITHMETIC_MISMATCH: 'DERIVATION_ARITHMETIC_MISMATCH',
  CONFLICT_STALE_DATA: 'CONFLICT_STALE_DATA',
  BANK_PROGRAM_HAS_OFFERS: 'BANK_PROGRAM_HAS_OFFERS',
  UNKNOWN_ENUMERATION_KEY: 'UNKNOWN_ENUMERATION_KEY',
  DEPRECATED_ENUMERATION_KEY: 'DEPRECATED_ENUMERATION_KEY',
  ENUMERATION_REGISTRY_UNAVAILABLE: 'ENUMERATION_REGISTRY_UNAVAILABLE',
  SEED_RATE_VERIFICATION_FAILED: 'SEED_RATE_VERIFICATION_FAILED',
  SEED_REQUIRES_SUPER_ADMIN: 'SEED_REQUIRES_SUPER_ADMIN',

  // --- Generic ---
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * HTTP status mapping. Reviewers can verify the OpenAPI contract matches.
 */
export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_ACCOUNT_INACTIVE: 403,
  AUTH_TOKEN_MISSING: 401,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_TOKEN_INVALID: 401,
  AUTH_REFRESH_INVALID: 401,
  FORBIDDEN: 403,
  MUST_CHANGE_PASSWORD: 403,
  INVALID_CURRENT_PASSWORD: 401,

  PASSWORD_TOO_SHORT: 422,
  PASSWORD_TOO_LONG: 422,
  PASSWORD_BREACHED: 422,
  PASSWORD_ON_COMMON_LIST: 422,
  PASSWORD_BREACH_CHECK_UNAVAILABLE: 503,
  PASSWORD_REUSES_RESET_VALUE: 422,

  DUPLICATE_ENTRY: 409,
  NOT_FOUND: 404,
  VALIDATION_FAILED: 422,
  CANNOT_SELF_MODIFY: 403,
  SUPER_ADMIN_FLOOR_VIOLATED: 403,

  BANK_PROGRAM_NOT_FOUND: 404,
  PROGRAM_CODE_ALREADY_IN_USE: 409,
  INVALID_VARIABLE_RATE_CONFIGURATION: 422,
  INVALID_QUALITATIVE_REVIEW_CEILING: 422,
  QUALITATIVE_REVIEW_CEILING_BELOW_BASE: 422,
  DERIVATION_ARITHMETIC_MISMATCH: 422,
  CONFLICT_STALE_DATA: 409,
  BANK_PROGRAM_HAS_OFFERS: 409,
  UNKNOWN_ENUMERATION_KEY: 422,
  DEPRECATED_ENUMERATION_KEY: 422,
  ENUMERATION_REGISTRY_UNAVAILABLE: 503,
  SEED_RATE_VERIFICATION_FAILED: 422,
  SEED_REQUIRES_SUPER_ADMIN: 403,

  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
};

export const ALL_ERROR_CODES: readonly ErrorCode[] = Object.values(ERROR_CODES);
