/**
 * Stable error codes for the admin + mobile API.
 * Constitution Principle III: no English strings cross the API boundary.
 * Adding a code is a same-PR operation across three files:
 *   1. this file
 *   2. admin/src/i18n/error-codes.ar-EG.json
 *   3. admin/src/i18n/error-codes.en-US.json
 */
export const ERROR_CODES = {
  // --- Auth / Session ---
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  MUST_CHANGE_PASSWORD: 'MUST_CHANGE_PASSWORD',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',

  // --- Password policy ---
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',
  PASSWORD_BREACHED: 'PASSWORD_BREACHED',
  PASSWORD_ON_COMMON_LIST: 'PASSWORD_ON_COMMON_LIST',
  PASSWORD_BREACH_CHECK_UNAVAILABLE: 'PASSWORD_BREACH_CHECK_UNAVAILABLE',
  PASSWORD_REUSES_RESET_VALUE: 'PASSWORD_REUSES_RESET_VALUE',

  // --- User management ---
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  CANNOT_SELF_MODIFY: 'CANNOT_SELF_MODIFY',
  SUPER_ADMIN_FLOOR_VIOLATED: 'SUPER_ADMIN_FLOOR_VIOLATED',

  // --- Bank programs (feature 002) ---
  BANK_PROGRAM_NOT_FOUND: 'BANK_PROGRAM_NOT_FOUND',
  PROGRAM_CODE_ALREADY_IN_USE: 'PROGRAM_CODE_ALREADY_IN_USE',
  INVALID_VARIABLE_RATE_CONFIGURATION: 'INVALID_VARIABLE_RATE_CONFIGURATION',
  INVALID_QUALITATIVE_REVIEW_CEILING: 'INVALID_QUALITATIVE_REVIEW_CEILING',
  QUALITATIVE_REVIEW_CEILING_BELOW_BASE: 'QUALITATIVE_REVIEW_CEILING_BELOW_BASE',
  DERIVATION_ARITHMETIC_MISMATCH: 'DERIVATION_ARITHMETIC_MISMATCH',
  CONFLICT_STALE_DATA: 'CONFLICT_STALE_DATA',
  BANK_PROGRAM_HAS_OFFERS: 'BANK_PROGRAM_HAS_OFFERS',
  UNKNOWN_ENUMERATION_KEY: 'UNKNOWN_ENUMERATION_KEY',
  DEPRECATED_ENUMERATION_KEY: 'DEPRECATED_ENUMERATION_KEY',
  ENUMERATION_REGISTRY_UNAVAILABLE: 'ENUMERATION_REGISTRY_UNAVAILABLE',
  SEED_RATE_VERIFICATION_FAILED: 'SEED_RATE_VERIFICATION_FAILED',
  SEED_REQUIRES_SUPER_ADMIN: 'SEED_REQUIRES_SUPER_ADMIN',

  // --- Matching engine (feature 003) ---
  NO_MATCHING_PROGRAMS: 'NO_MATCHING_PROGRAMS',
  INCOME_TOO_LOW: 'INCOME_TOO_LOW',
  AGE_NOT_ELIGIBLE: 'AGE_NOT_ELIGIBLE',
  DBR_EXCEEDED: 'DBR_EXCEEDED',
  TENOR_OUT_OF_RANGE: 'TENOR_OUT_OF_RANGE',
  AMOUNT_OUT_OF_RANGE: 'AMOUNT_OUT_OF_RANGE',
  CURRENCY_NOT_SUPPORTED: 'CURRENCY_NOT_SUPPORTED',
  MISSING_CD_RECORD: 'MISSING_CD_RECORD',
  MISSING_CAR_LOAN_RECORD: 'MISSING_CAR_LOAN_RECORD',
  MISSING_BANK_STATEMENT: 'MISSING_BANK_STATEMENT',
  INCOME_LOOKUP_FAILED: 'INCOME_LOOKUP_FAILED',
  MATCHING_ENGINE_ERROR: 'MATCHING_ENGINE_ERROR',
  IDEMPOTENCY_KEY_MISMATCH: 'IDEMPOTENCY_KEY_MISMATCH',
  UNAUTHENTICATED: 'UNAUTHENTICATED',

  // --- Mobile HMAC auth (feature 003) ---
  HMAC_CLIENT_UNKNOWN: 'HMAC_CLIENT_UNKNOWN',
  HMAC_HEADER_MISSING: 'HMAC_HEADER_MISSING',
  HMAC_SIGNATURE_INVALID: 'HMAC_SIGNATURE_INVALID',
  HMAC_TIMESTAMP_SKEW: 'HMAC_TIMESTAMP_SKEW',
  HMAC_NONCE_REPLAY: 'HMAC_NONCE_REPLAY',
  HMAC_BODY_HASH_MISMATCH: 'HMAC_BODY_HASH_MISMATCH',

  // --- Scoring versions / analytics (feature 004) ---
  SCORING_VERSION_CONCURRENT_PROMOTION: 'SCORING_VERSION_CONCURRENT_PROMOTION',
  SCORING_VERSION_NOT_FOUND: 'SCORING_VERSION_NOT_FOUND',
  SCORING_VERSION_NO_ACTIVE: 'SCORING_VERSION_NO_ACTIVE',
  ANALYTICS_WINDOW_TOO_LARGE: 'ANALYTICS_WINDOW_TOO_LARGE',

  // --- Lead management (feature 005) ---
  ACTIVITY_FORBIDDEN_NOT_ASSIGNED: 'ACTIVITY_FORBIDDEN_NOT_ASSIGNED',
  INVALID_ACTIVITY_REASON: 'INVALID_ACTIVITY_REASON',
  REASON_DETAILS_REQUIRED: 'REASON_DETAILS_REQUIRED',
  DURATION_REQUIRED_FOR_CALL: 'DURATION_REQUIRED_FOR_CALL',
  FOLLOWUP_IN_PAST: 'FOLLOWUP_IN_PAST',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',

  // --- Platform enumerations (feature 006) ---
  ENUMERATION_KEY_DUPLICATE: 'ENUMERATION_KEY_DUPLICATE',
  ENUMERATION_SYSTEM_ONLY: 'ENUMERATION_SYSTEM_ONLY',

  // --- User proceed (feature 008) ---
  BANK_OFFER_NOT_FOUND: 'BANK_OFFER_NOT_FOUND',
  OFFER_NOT_FOR_APPLICATION: 'OFFER_NOT_FOR_APPLICATION',
  ALREADY_PROCEEDED: 'ALREADY_PROCEEDED',
  APPLICATION_NOT_MATCHED: 'APPLICATION_NOT_MATCHED',
  NONE_TRANSFER_UNSAFE: 'NONE_TRANSFER_UNSAFE',

  // --- Banks (feature 007) ---
  BANK_NOT_FOUND: 'BANK_NOT_FOUND',
  BANK_CODE_DUPLICATE: 'BANK_CODE_DUPLICATE',
  BANK_CODE_INVALID_FORMAT: 'BANK_CODE_INVALID_FORMAT',
  BANK_HAS_PROGRAMS: 'BANK_HAS_PROGRAMS',
  BANK_CONFLICT_STALE_DATA: 'BANK_CONFLICT_STALE_DATA',

  // --- Generic ---
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * HTTP status mapping. Reviewers can verify the OpenAPI contract matches.
 */
export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_ACCOUNT_INACTIVE: 403,
  AUTH_TOKEN_MISSING: 401,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_TOKEN_INVALID: 401,
  AUTH_REFRESH_INVALID: 401,
  FORBIDDEN: 403,
  MUST_CHANGE_PASSWORD: 403,
  INVALID_CURRENT_PASSWORD: 401,

  PASSWORD_TOO_SHORT: 422,
  PASSWORD_TOO_LONG: 422,
  PASSWORD_BREACHED: 422,
  PASSWORD_ON_COMMON_LIST: 422,
  PASSWORD_BREACH_CHECK_UNAVAILABLE: 503,
  PASSWORD_REUSES_RESET_VALUE: 422,

  DUPLICATE_ENTRY: 409,
  NOT_FOUND: 404,
  VALIDATION_FAILED: 422,
  CANNOT_SELF_MODIFY: 403,
  SUPER_ADMIN_FLOOR_VIOLATED: 403,

  BANK_PROGRAM_NOT_FOUND: 404,
  PROGRAM_CODE_ALREADY_IN_USE: 409,
  INVALID_VARIABLE_RATE_CONFIGURATION: 422,
  INVALID_QUALITATIVE_REVIEW_CEILING: 422,
  QUALITATIVE_REVIEW_CEILING_BELOW_BASE: 422,
  DERIVATION_ARITHMETIC_MISMATCH: 422,
  CONFLICT_STALE_DATA: 409,
  BANK_PROGRAM_HAS_OFFERS: 409,
  UNKNOWN_ENUMERATION_KEY: 422,
  DEPRECATED_ENUMERATION_KEY: 422,
  ENUMERATION_REGISTRY_UNAVAILABLE: 503,
  SEED_RATE_VERIFICATION_FAILED: 422,
  SEED_REQUIRES_SUPER_ADMIN: 403,

  NO_MATCHING_PROGRAMS: 200,
  INCOME_TOO_LOW: 200,
  AGE_NOT_ELIGIBLE: 200,
  DBR_EXCEEDED: 200,
  TENOR_OUT_OF_RANGE: 200,
  AMOUNT_OUT_OF_RANGE: 200,
  CURRENCY_NOT_SUPPORTED: 200,
  MISSING_CD_RECORD: 200,
  MISSING_CAR_LOAN_RECORD: 200,
  MISSING_BANK_STATEMENT: 200,
  INCOME_LOOKUP_FAILED: 200,
  MATCHING_ENGINE_ERROR: 500,
  IDEMPOTENCY_KEY_MISMATCH: 409,
  UNAUTHENTICATED: 401,

  HMAC_CLIENT_UNKNOWN: 401,
  HMAC_HEADER_MISSING: 401,
  HMAC_SIGNATURE_INVALID: 401,
  HMAC_TIMESTAMP_SKEW: 401,
  HMAC_NONCE_REPLAY: 401,
  HMAC_BODY_HASH_MISMATCH: 401,

  SCORING_VERSION_CONCURRENT_PROMOTION: 409,
  SCORING_VERSION_NOT_FOUND: 404,
  SCORING_VERSION_NO_ACTIVE: 503,
  ANALYTICS_WINDOW_TOO_LARGE: 400,

  ACTIVITY_FORBIDDEN_NOT_ASSIGNED: 403,
  INVALID_ACTIVITY_REASON: 422,
  REASON_DETAILS_REQUIRED: 422,
  DURATION_REQUIRED_FOR_CALL: 422,
  FOLLOWUP_IN_PAST: 422,
  FILE_TOO_LARGE: 413,
  FILE_TYPE_NOT_ALLOWED: 415,

  ENUMERATION_KEY_DUPLICATE: 409,
  ENUMERATION_SYSTEM_ONLY: 403,

  BANK_NOT_FOUND: 404,
  BANK_CODE_DUPLICATE: 409,
  BANK_CODE_INVALID_FORMAT: 422,
  BANK_HAS_PROGRAMS: 409,
  BANK_CONFLICT_STALE_DATA: 409,

  BANK_OFFER_NOT_FOUND: 404,
  OFFER_NOT_FOR_APPLICATION: 409,
  ALREADY_PROCEEDED: 409,
  APPLICATION_NOT_MATCHED: 409,
  NONE_TRANSFER_UNSAFE: 422,

  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
};

export const ALL_ERROR_CODES: readonly ErrorCode[] = Object.values(ERROR_CODES);
