/**
 * Stable error codes for the admin + mobile API.
 * Constitution Principle III: no English strings cross the API boundary.
 * Adding a code is a same-PR operation across three files:
 *   1. this file
 *   2. admin/src/i18n/error-codes.ar-EG.json
 *   3. admin/src/i18n/error-codes.en-US.json
 */
export const ERROR_CODES = {
  // --- Auth / Session ---
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  MUST_CHANGE_PASSWORD: 'MUST_CHANGE_PASSWORD',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',

  // --- Password policy ---
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORD_TOO_LONG: 'PASSWORD_TOO_LONG',
  PASSWORD_BREACHED: 'PASSWORD_BREACHED',
  PASSWORD_ON_COMMON_LIST: 'PASSWORD_ON_COMMON_LIST',
  PASSWORD_BREACH_CHECK_UNAVAILABLE: 'PASSWORD_BREACH_CHECK_UNAVAILABLE',
  PASSWORD_REUSES_RESET_VALUE: 'PASSWORD_REUSES_RESET_VALUE',

  // --- User management ---
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  CANNOT_SELF_MODIFY: 'CANNOT_SELF_MODIFY',
  SUPER_ADMIN_FLOOR_VIOLATED: 'SUPER_ADMIN_FLOOR_VIOLATED',

  // --- Bank programs (feature 002) ---
  BANK_PROGRAM_NOT_FOUND: 'BANK_PROGRAM_NOT_FOUND',
  PROGRAM_CODE_ALREADY_IN_USE: 'PROGRAM_CODE_ALREADY_IN_USE',
  INVALID_VARIABLE_RATE_CONFIGURATION: 'INVALID_VARIABLE_RATE_CONFIGURATION',
  INVALID_QUALITATIVE_REVIEW_CEILING: 'INVALID_QUALITATIVE_REVIEW_CEILING',
  QUALITATIVE_REVIEW_CEILING_BELOW_BASE: 'QUALITATIVE_REVIEW_CEILING_BELOW_BASE',
  DERIVATION_ARITHMETIC_MISMATCH: 'DERIVATION_ARITHMETIC_MISMATCH',
  CONFLICT_STALE_DATA: 'CONFLICT_STALE_DATA',
  BANK_PROGRAM_HAS_OFFERS: 'BANK_PROGRAM_HAS_OFFERS',
  UNKNOWN_ENUMERATION_KEY: 'UNKNOWN_ENUMERATION_KEY',
  DEPRECATED_ENUMERATION_KEY: 'DEPRECATED_ENUMERATION_KEY',
  ENUMERATION_REGISTRY_UNAVAILABLE: 'ENUMERATION_REGISTRY_UNAVAILABLE',
  SEED_RATE_VERIFICATION_FAILED: 'SEED_RATE_VERIFICATION_FAILED',
  SEED_REQUIRES_SUPER_ADMIN: 'SEED_REQUIRES_SUPER_ADMIN',

  // --- Matching engine (feature 003) ---
  NO_MATCHING_PROGRAMS: 'NO_MATCHING_PROGRAMS',
  INCOME_TOO_LOW: 'INCOME_TOO_LOW',
  AGE_NOT_ELIGIBLE: 'AGE_NOT_ELIGIBLE',
  DBR_EXCEEDED: 'DBR_EXCEEDED',
  TENOR_OUT_OF_RANGE: 'TENOR_OUT_OF_RANGE',
  AMOUNT_OUT_OF_RANGE: 'AMOUNT_OUT_OF_RANGE',
  CURRENCY_NOT_SUPPORTED: 'CURRENCY_NOT_SUPPORTED',
  MISSING_CD_RECORD: 'MISSING_CD_RECORD',
  MISSING_CAR_LOAN_RECORD: 'MISSING_CAR_LOAN_RECORD',
  MISSING_BANK_STATEMENT: 'MISSING_BANK_STATEMENT',
  INCOME_LOOKUP_FAILED: 'INCOME_LOOKUP_FAILED',
  MATCHING_ENGINE_ERROR: 'MATCHING_ENGINE_ERROR',
  IDEMPOTENCY_KEY_MISMATCH: 'IDEMPOTENCY_KEY_MISMATCH',
  UNAUTHENTICATED: 'UNAUTHENTICATED',

  // --- Scoring versions / analytics (feature 004) ---
  SCORING_VERSION_CONCURRENT_PROMOTION: 'SCORING_VERSION_CONCURRENT_PROMOTION',
  SCORING_VERSION_NOT_FOUND: 'SCORING_VERSION_NOT_FOUND',
  SCORING_VERSION_NO_ACTIVE: 'SCORING_VERSION_NO_ACTIVE',

  // --- Platform enumerations (feature 006) ---
  ENUMERATION_KEY_DUPLICATE: 'ENUMERATION_KEY_DUPLICATE',
  ENUMERATION_SYSTEM_ONLY: 'ENUMERATION_SYSTEM_ONLY',
  /** Loan categories were submitted for an enumeration type that has no such axis. */
  ENUMERATION_CATEGORIES_NOT_APPLICABLE: 'ENUMERATION_CATEGORIES_NOT_APPLICABLE',
  /** A question template was submitted for an enumeration type that has no such axis. */
  ENUMERATION_QUESTIONS_NOT_APPLICABLE: 'ENUMERATION_QUESTIONS_NOT_APPLICABLE',
  /** A catalog question template named codes that are in no question, active or not. */
  ENUMERATION_QUESTION_UNKNOWN: 'ENUMERATION_QUESTION_UNKNOWN',

  // --- User proceed (feature 008) ---
  BANK_OFFER_NOT_FOUND: 'BANK_OFFER_NOT_FOUND',
  OFFER_NOT_FOR_APPLICATION: 'OFFER_NOT_FOR_APPLICATION',
  ALREADY_PROCEEDED: 'ALREADY_PROCEEDED',
  APPLICATION_NOT_MATCHED: 'APPLICATION_NOT_MATCHED',
  NONE_TRANSFER_UNSAFE: 'NONE_TRANSFER_UNSAFE',

  // --- Saved offers (Saved Offers screen) ---
  SAVED_OFFER_NOT_FOUND: 'SAVED_OFFER_NOT_FOUND',

  // --- Banks (feature 007) ---
  BANK_NOT_FOUND: 'BANK_NOT_FOUND',
  BANK_NAME_DUPLICATE: 'BANK_NAME_DUPLICATE',
  BANK_HAS_PROGRAMS: 'BANK_HAS_PROGRAMS',
  BANK_CONFLICT_STALE_DATA: 'BANK_CONFLICT_STALE_DATA',

  // --- Customer mobile auth (v1.7.0) ---
  CUSTOMER_PHONE_ALREADY_REGISTERED: 'CUSTOMER_PHONE_ALREADY_REGISTERED',
  CUSTOMER_EMAIL_ALREADY_REGISTERED: 'CUSTOMER_EMAIL_ALREADY_REGISTERED',
  CUSTOMER_INVALID_CREDENTIALS: 'CUSTOMER_INVALID_CREDENTIALS',
  CUSTOMER_ACCOUNT_INACTIVE: 'CUSTOMER_ACCOUNT_INACTIVE',
  CUSTOMER_REFRESH_INVALID: 'CUSTOMER_REFRESH_INVALID',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_PHONE_INVALID: 'CUSTOMER_PHONE_INVALID',

  // --- Feature 008 — Two-Path Registration (Constitution v1.8.0 / Principle XIII) ---
  // OTP lifecycle
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_CONSUMED: 'OTP_CONSUMED',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  OTP_PURPOSE_LOGIN_FORBIDDEN: 'OTP_PURPOSE_LOGIN_FORBIDDEN',
  // Verified-mobile token (PHONE-signup pre-customer bearer)
  VERIFIED_MOBILE_TOKEN_INVALID: 'VERIFIED_MOBILE_TOKEN_INVALID',
  VERIFIED_MOBILE_TOKEN_EXPIRED: 'VERIFIED_MOBILE_TOKEN_EXPIRED',
  VERIFIED_MOBILE_TOKEN_CONSUMED: 'VERIFIED_MOBILE_TOKEN_CONSUMED',
  // Social provider verification
  SOCIAL_TOKEN_INVALID: 'SOCIAL_TOKEN_INVALID',
  SOCIAL_TOKEN_EXPIRED: 'SOCIAL_TOKEN_EXPIRED',
  SOCIAL_PROVIDER_UNAVAILABLE: 'SOCIAL_PROVIDER_UNAVAILABLE',
  SOCIAL_SESSION_INVALID: 'SOCIAL_SESSION_INVALID',
  SOCIAL_SESSION_EXPIRED: 'SOCIAL_SESSION_EXPIRED',
  SOCIAL_SESSION_CONSUMED: 'SOCIAL_SESSION_CONSUMED',
  // Login lockout (10 failures / 15 min → 30 min)
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  PASSWORD_NOT_SET: 'PASSWORD_NOT_SET',
  PASSWORD_SAME_AS_OLD: 'PASSWORD_SAME_AS_OLD',
  // Profile-completion flow (Principle XXXVII)
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  PROFILE_FIELD_IMMUTABLE: 'PROFILE_FIELD_IMMUTABLE',
  PROFILE_ID_DOCS_MISSING: 'PROFILE_ID_DOCS_MISSING',
  // Select-offer commitment gate: optional at signup; the profile photo and
  // National ID (front+back) are required when the customer proceeds with a
  // bank offer — not at the matching call (POST /v1/apply).
  NATIONAL_ID_REQUIRED: 'NATIONAL_ID_REQUIRED',
  PROFILE_PHOTO_REQUIRED: 'PROFILE_PHOTO_REQUIRED',
  PASSWORD_REQUIRED_FOR_PHONE_PROFILE: 'PASSWORD_REQUIRED_FOR_PHONE_PROFILE',
  PASSWORD_FORBIDDEN_FOR_SOCIAL_PROFILE: 'PASSWORD_FORBIDDEN_FOR_SOCIAL_PROFILE',
  PHONE_MUTATION_ON_PHONE_CUSTOMER_FORBIDDEN: 'PHONE_MUTATION_ON_PHONE_CUSTOMER_FORBIDDEN',
  PASSWORD_CHANGE_FORBIDDEN_FOR_SOCIAL: 'PASSWORD_CHANGE_FORBIDDEN_FOR_SOCIAL',
  // Loan submission validation
  AGE_INVALID: 'AGE_INVALID',
  DOCUMENTS_MISSING: 'DOCUMENTS_MISSING',
  DOCUMENTS_NOT_OWNED: 'DOCUMENTS_NOT_OWNED',
  BANK_PROGRAM_INVALID: 'BANK_PROGRAM_INVALID',

  // --- Document upload constraints ---
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',

  // --- Customer document upload (v1.7.0) ---
  DOCUMENT_OWNERSHIP_MISMATCH: 'DOCUMENT_OWNERSHIP_MISMATCH',
  DOCUMENT_NOT_PENDING: 'DOCUMENT_NOT_PENDING',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',

  // --- Support (v1.7.0) ---
  SUPPORT_REQUEST_NOT_FOUND: 'SUPPORT_REQUEST_NOT_FOUND',
  SUPPORT_REQUEST_ALREADY_RESOLVED: 'SUPPORT_REQUEST_ALREADY_RESOLVED',
  SUPPORT_CONFIG_NOT_FOUND: 'SUPPORT_CONFIG_NOT_FOUND',

  // --- Onboarding (v1.7.0) ---
  ONBOARDING_SCREEN_NOT_FOUND: 'ONBOARDING_SCREEN_NOT_FOUND',
  ONBOARDING_ORDER_DUPLICATE: 'ONBOARDING_ORDER_DUPLICATE',

  // --- Telemetry (v1.7.0) ---
  TELEMETRY_EVENT_NOT_ALLOWED: 'TELEMETRY_EVENT_NOT_ALLOWED',

  // --- Dynamic questionnaire & matching (Feature 00X, Constitution V v4.1.0) ---
  QUESTIONNAIRE_NOT_PUBLISHED: 'QUESTIONNAIRE_NOT_PUBLISHED',
  QUESTION_GROUP_NOT_FOUND: 'QUESTION_GROUP_NOT_FOUND',
  QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
  QUESTION_OPTION_NOT_FOUND: 'QUESTION_OPTION_NOT_FOUND',
  UNKNOWN_QUESTION_CODE: 'UNKNOWN_QUESTION_CODE',
  UNKNOWN_OPTION_CODE: 'UNKNOWN_OPTION_CODE',
  ENABLED_WHEN_INVALID: 'ENABLED_WHEN_INVALID',
  QUESTION_IN_USE: 'QUESTION_IN_USE',
  QUESTION_OPTION_IN_USE: 'QUESTION_OPTION_IN_USE',
  QUESTION_GROUP_NOT_EMPTY: 'QUESTION_GROUP_NOT_EMPTY',
  REQUIRED_ANSWER_MISSING: 'REQUIRED_ANSWER_MISSING',
  PROGRAM_NO_LONGER_MATCHES: 'PROGRAM_NO_LONGER_MATCHES',
  // Scoring weights (MVP — per-answer points, direct save)
  WEIGHT_SET_NOT_FOUND: 'WEIGHT_SET_NOT_FOUND',
  WEIGHTS_UNKNOWN_OPTION: 'WEIGHTS_UNKNOWN_OPTION',
  WEIGHTS_QUESTION_WEIGHT_SUM_INVALID: 'WEIGHTS_QUESTION_WEIGHT_SUM_INVALID',
  WEIGHTS_ANSWER_SCORE_OUT_OF_RANGE: 'WEIGHTS_ANSWER_SCORE_OUT_OF_RANGE',
  /**
   * A weighted question carries no rule for its own type (v14.0.0): no option
   * scores, no numeric bands, no text presence score. It would consume its share
   * of the denominator and never be able to earn anything — a silent cap.
   */
  WEIGHTS_MISSING_RULE: 'WEIGHTS_MISSING_RULE',
  /** NUMERIC bands missing, out of order, overlapping, gapped, or malformed. */
  WEIGHTS_NUMERIC_BANDS_INVALID: 'WEIGHTS_NUMERIC_BANDS_INVALID',
  /** A rule block on a question of the wrong type, or an unknown aggregation. */
  WEIGHTS_RULE_TYPE_MISMATCH: 'WEIGHTS_RULE_TYPE_MISMATCH',
  /**
   * A weighted question is not in the program's catalog set — the questions a
   * `program_name` scores on under this loan category (`/program-catalog/:key`).
   * Every bank program sharing a catalog name scores on the SAME questions and
   * differs only in weights, so the question set is not the bank program's to
   * choose. Also raised when the program has no `programNameKey` at all (nothing
   * to scope by) or the catalog set for its category is empty: the meta carries
   * `programNameKey` + `allowedQuestionCodes` so the admin screen can say which.
   */
  WEIGHTS_QUESTION_NOT_IN_CATALOG: 'WEIGHTS_QUESTION_NOT_IN_CATALOG',

  // --- Feature 010 — simple program setup, banded DBR & calculator ---
  // Banded DBR + program ranges (admin)
  DBR_BANDS_INVALID: 'DBR_BANDS_INVALID',
  DBR_BAND_CAP_OUT_OF_RANGE: 'DBR_BAND_CAP_OUT_OF_RANGE',
  PROGRAM_RANGE_INVALID: 'PROGRAM_RANGE_INVALID',
  /** Bank program named something outside the predefined `program_name` catalog. */
  PROGRAM_NAME_KEY_UNKNOWN: 'PROGRAM_NAME_KEY_UNKNOWN',
  /**
   * The catalog name exists and is live, but is not assigned to the loan
   * category the program is being saved under (Program catalog → Loan
   * categories). `meta.assignedCategories` is the set it IS offered under —
   * empty means the name is parked.
   */
  PROGRAM_NAME_KEY_NOT_IN_CATEGORY: 'PROGRAM_NAME_KEY_NOT_IN_CATEGORY',
  // Typed questions + typed answers
  ANSWER_TYPE_MISMATCH: 'ANSWER_TYPE_MISMATCH',
  ANSWER_OUT_OF_RANGE: 'ANSWER_OUT_OF_RANGE',
  ANSWER_TOO_LONG: 'ANSWER_TOO_LONG',
  ANSWER_REQUIRED: 'ANSWER_REQUIRED',
  QUESTION_TYPE_RULES_INVALID: 'QUESTION_TYPE_RULES_INVALID',
  QUESTION_TYPE_NOT_SCOREABLE: 'QUESTION_TYPE_NOT_SCOREABLE',
  // Money-field bindings (code constants — never a Question column, A33)
  MONEY_FIELD_BINDING_MISSING: 'MONEY_FIELD_BINDING_MISSING',
  MONEY_FIGURE_MISSING: 'MONEY_FIGURE_MISSING',
  // Itemised obligations: the stated total disagreed with the sum of the per-debt
  // answers. The sum is authoritative, so this is a tampered or stale client —
  // never a user mistake, because the total is not typed by hand.
  OBLIGATIONS_TOTAL_MISMATCH: 'OBLIGATIONS_TOTAL_MISMATCH',
  // Calculator
  CALCULATOR_INPUT_INVALID: 'CALCULATOR_INPUT_INVALID',
  CALCULATOR_PROGRAM_INACTIVE: 'CALCULATOR_PROGRAM_INACTIVE',
  PROGRAM_MISCONFIGURED: 'PROGRAM_MISCONFIGURED',
  // Reason codes: never thrown — returned inside a 200 payload when a program is
  // listed without figures (FR-024). `PROGRAM_MISCONFIGURED` doubles as a reason.
  NO_RECOGNISED_INCOME: 'NO_RECOGNISED_INCOME',
  OBLIGATIONS_EXCEED_ALLOWANCE: 'OBLIGATIONS_EXCEED_ALLOWANCE',
  BELOW_PROGRAM_MIN_AMOUNT: 'BELOW_PROGRAM_MIN_AMOUNT',
  AGE_AT_MATURITY: 'AGE_AT_MATURITY',
  CURRENCY_NOT_OFFERED: 'CURRENCY_NOT_OFFERED',
  // Disclaimer shown alongside every indicative figure (not an error)
  INDICATIVE_ESTIMATE_NOT_AN_OFFER: 'INDICATIVE_ESTIMATE_NOT_AN_OFFER',

  // --- Feature 011 — income-surrogate rule builder (admin) ---
  // Rule save rejections (FR-006 … FR-012). Every one names the offending row so
  // the admin form can point at it rather than reporting "the table is invalid".
  /** A table method was selected and its table is absent or empty (FR-009). */
  INCOME_RULE_EMPTY: 'INCOME_RULE_EMPTY',
  /** A row's `incomeEGP` is ≤ 0 or not Decimal-parseable (FR-010). */
  INCOME_RULE_INCOME_INVALID: 'INCOME_RULE_INCOME_INVALID',
  /** Two rows of a key table carry the same registry key (FR-006). */
  INCOME_RULE_DUPLICATE_KEY: 'INCOME_RULE_DUPLICATE_KEY',
  /**
   * A key table row names a key that is not an ACTIVE member of the method's
   * platform enumeration. Fails CLOSED (AS-1.9): the engine's lookup is by key,
   * so a dead key would resolve to nothing for every applicant, silently.
   */
  INCOME_RULE_UNKNOWN_KEY: 'INCOME_RULE_UNKNOWN_KEY',
  /**
   * Band edges unordered, gapped, overlapping, or an OPEN band with rows after it
   * (FR-008). `meta.reason` names which, `meta.index` the offending band. A closed
   * LAST band is legal — it means the rule yields nothing above that edge.
   */
  INCOME_RULE_BANDS_INVALID: 'INCOME_RULE_BANDS_INVALID',
  /** Per-rule DBR override outside (0, 100] (FR-012). */
  INCOME_RULE_DBR_OVERRIDE_INVALID: 'INCOME_RULE_DBR_OVERRIDE_INVALID',
  /**
   * A `valueSources` marker names a dot-path that is not on the program's
   * numeric allow-list AND never was on the stored one. A path that WAS markable
   * and no longer is (a row deleted, a method switched) is stale, not unknown: it
   * is pruned with the number it described, because rejecting it would trap the
   * admin behind a control that no longer exists (research R8).
   */
  VALUE_SOURCE_PATH_UNKNOWN: 'VALUE_SOURCE_PATH_UNKNOWN',
  /**
   * A `valueSources` entry carries something other than `team_estimated`. Its own
   * code, not `VALUE_SOURCE_PATH_UNKNOWN`: the path is fine, so "reload the
   * program and try again" would send the admin to fix the one thing that is right.
   */
  VALUE_SOURCE_VALUE_INVALID: 'VALUE_SOURCE_VALUE_INVALID',
  /**
   * Activation refused: the program still carries team-estimated numbers
   * (FR-033). `meta.paths` lists EVERY one, not the first — the admin has to ask
   * the bank about all of them, and a one-at-a-time reveal wastes a round trip.
   */
  PROGRAM_HAS_ESTIMATED_VALUES: 'PROGRAM_HAS_ESTIMATED_VALUES',
  /**
   * Publish/tree WARNING payload (never thrown): a surrogate fact's bound
   * question is missing, inactive, the wrong type, drifted from its registry, or
   * not assigned to `personal`. Sibling of `MONEY_FIELD_BINDING_MISSING` —
   * publishing is never blocked, or a half-renamed binding would lock the pool.
   */
  SURROGATE_FACT_BINDING_MISSING: 'SURROGATE_FACT_BINDING_MISSING',
  // Reason codes: returned inside a 200 payload, the program still listed and
  // still ranked (FR-022, FR-024). They exist as a PAIR because the two lead to
  // different admin actions — assign the question vs. add the table row.
  /** The rule's fact is absent from the profile — not asked, or skipped (FR-020). */
  SURROGATE_FACT_MISSING: 'SURROGATE_FACT_MISSING',
  /** The fact was answered, but no key matched / the value fell in no band. */
  SURROGATE_NO_MATCHING_ROW: 'SURROGATE_NO_MATCHING_ROW',

  // --- Generic ---
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * HTTP status mapping. Reviewers can verify the OpenAPI contract matches.
 */
export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_ACCOUNT_INACTIVE: 403,
  AUTH_TOKEN_MISSING: 401,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_TOKEN_INVALID: 401,
  AUTH_REFRESH_INVALID: 401,
  FORBIDDEN: 403,
  MUST_CHANGE_PASSWORD: 403,
  INVALID_CURRENT_PASSWORD: 401,

  PASSWORD_TOO_SHORT: 422,
  PASSWORD_TOO_LONG: 422,
  PASSWORD_BREACHED: 422,
  PASSWORD_ON_COMMON_LIST: 422,
  PASSWORD_BREACH_CHECK_UNAVAILABLE: 503,
  PASSWORD_REUSES_RESET_VALUE: 422,

  DUPLICATE_ENTRY: 409,
  NOT_FOUND: 404,
  VALIDATION_FAILED: 422,
  CANNOT_SELF_MODIFY: 403,
  SUPER_ADMIN_FLOOR_VIOLATED: 403,

  BANK_PROGRAM_NOT_FOUND: 404,
  PROGRAM_CODE_ALREADY_IN_USE: 409,
  INVALID_VARIABLE_RATE_CONFIGURATION: 422,
  INVALID_QUALITATIVE_REVIEW_CEILING: 422,
  QUALITATIVE_REVIEW_CEILING_BELOW_BASE: 422,
  DERIVATION_ARITHMETIC_MISMATCH: 422,
  CONFLICT_STALE_DATA: 409,
  BANK_PROGRAM_HAS_OFFERS: 409,
  UNKNOWN_ENUMERATION_KEY: 422,
  DEPRECATED_ENUMERATION_KEY: 422,
  ENUMERATION_REGISTRY_UNAVAILABLE: 503,
  SEED_RATE_VERIFICATION_FAILED: 422,
  SEED_REQUIRES_SUPER_ADMIN: 403,

  NO_MATCHING_PROGRAMS: 200,
  INCOME_TOO_LOW: 200,
  AGE_NOT_ELIGIBLE: 200,
  DBR_EXCEEDED: 200,
  TENOR_OUT_OF_RANGE: 200,
  AMOUNT_OUT_OF_RANGE: 200,
  CURRENCY_NOT_SUPPORTED: 200,
  MISSING_CD_RECORD: 200,
  MISSING_CAR_LOAN_RECORD: 200,
  MISSING_BANK_STATEMENT: 200,
  INCOME_LOOKUP_FAILED: 200,
  MATCHING_ENGINE_ERROR: 500,
  IDEMPOTENCY_KEY_MISMATCH: 409,
  UNAUTHENTICATED: 401,

  SCORING_VERSION_CONCURRENT_PROMOTION: 409,
  SCORING_VERSION_NOT_FOUND: 404,
  SCORING_VERSION_NO_ACTIVE: 503,

  ENUMERATION_KEY_DUPLICATE: 409,
  ENUMERATION_SYSTEM_ONLY: 403,
  ENUMERATION_CATEGORIES_NOT_APPLICABLE: 422,
  ENUMERATION_QUESTIONS_NOT_APPLICABLE: 422,
  ENUMERATION_QUESTION_UNKNOWN: 422,

  BANK_NOT_FOUND: 404,
  BANK_NAME_DUPLICATE: 409,
  BANK_HAS_PROGRAMS: 409,
  BANK_CONFLICT_STALE_DATA: 409,

  BANK_OFFER_NOT_FOUND: 404,
  OFFER_NOT_FOR_APPLICATION: 409,
  ALREADY_PROCEEDED: 409,
  APPLICATION_NOT_MATCHED: 409,
  NONE_TRANSFER_UNSAFE: 422,

  SAVED_OFFER_NOT_FOUND: 404,

  CUSTOMER_PHONE_ALREADY_REGISTERED: 409,
  CUSTOMER_EMAIL_ALREADY_REGISTERED: 409,
  CUSTOMER_INVALID_CREDENTIALS: 401,
  CUSTOMER_ACCOUNT_INACTIVE: 403,
  CUSTOMER_REFRESH_INVALID: 401,
  CUSTOMER_NOT_FOUND: 404,
  CUSTOMER_PHONE_INVALID: 422,

  OTP_INVALID: 400,
  OTP_EXPIRED: 400,
  OTP_CONSUMED: 400,
  OTP_ATTEMPTS_EXCEEDED: 400,
  OTP_RATE_LIMITED: 429,
  OTP_PURPOSE_LOGIN_FORBIDDEN: 400,
  VERIFIED_MOBILE_TOKEN_INVALID: 401,
  VERIFIED_MOBILE_TOKEN_EXPIRED: 401,
  VERIFIED_MOBILE_TOKEN_CONSUMED: 401,
  SOCIAL_TOKEN_INVALID: 401,
  SOCIAL_TOKEN_EXPIRED: 401,
  SOCIAL_PROVIDER_UNAVAILABLE: 503,
  SOCIAL_SESSION_INVALID: 400,
  SOCIAL_SESSION_EXPIRED: 400,
  SOCIAL_SESSION_CONSUMED: 400,
  ACCOUNT_LOCKED: 423,
  PASSWORD_NOT_SET: 409,
  PASSWORD_SAME_AS_OLD: 422,
  PROFILE_INCOMPLETE: 409,
  PROFILE_FIELD_IMMUTABLE: 409,
  PROFILE_ID_DOCS_MISSING: 400,
  NATIONAL_ID_REQUIRED: 409,
  PROFILE_PHOTO_REQUIRED: 409,
  PASSWORD_REQUIRED_FOR_PHONE_PROFILE: 400,
  PASSWORD_FORBIDDEN_FOR_SOCIAL_PROFILE: 400,
  PHONE_MUTATION_ON_PHONE_CUSTOMER_FORBIDDEN: 403,
  PASSWORD_CHANGE_FORBIDDEN_FOR_SOCIAL: 403,
  AGE_INVALID: 422,
  DOCUMENTS_MISSING: 400,
  DOCUMENTS_NOT_OWNED: 403,
  BANK_PROGRAM_INVALID: 409,

  FILE_TOO_LARGE: 413,
  FILE_TYPE_NOT_ALLOWED: 415,
  DOCUMENT_OWNERSHIP_MISMATCH: 403,
  DOCUMENT_NOT_PENDING: 409,
  DOCUMENT_NOT_FOUND: 404,

  SUPPORT_REQUEST_NOT_FOUND: 404,
  SUPPORT_REQUEST_ALREADY_RESOLVED: 409,
  SUPPORT_CONFIG_NOT_FOUND: 404,

  ONBOARDING_SCREEN_NOT_FOUND: 404,
  ONBOARDING_ORDER_DUPLICATE: 409,

  TELEMETRY_EVENT_NOT_ALLOWED: 422,

  QUESTIONNAIRE_NOT_PUBLISHED: 404,
  QUESTION_GROUP_NOT_FOUND: 404,
  QUESTION_NOT_FOUND: 404,
  QUESTION_OPTION_NOT_FOUND: 404,
  UNKNOWN_QUESTION_CODE: 400,
  UNKNOWN_OPTION_CODE: 400,
  ENABLED_WHEN_INVALID: 422,
  QUESTION_IN_USE: 409,
  QUESTION_OPTION_IN_USE: 409,
  QUESTION_GROUP_NOT_EMPTY: 409,
  REQUIRED_ANSWER_MISSING: 422,
  PROGRAM_NO_LONGER_MATCHES: 409,
  WEIGHT_SET_NOT_FOUND: 404,
  WEIGHTS_UNKNOWN_OPTION: 422,
  WEIGHTS_QUESTION_WEIGHT_SUM_INVALID: 422,
  WEIGHTS_ANSWER_SCORE_OUT_OF_RANGE: 422,
  WEIGHTS_MISSING_RULE: 422,
  WEIGHTS_NUMERIC_BANDS_INVALID: 422,
  WEIGHTS_RULE_TYPE_MISMATCH: 422,
  WEIGHTS_QUESTION_NOT_IN_CATALOG: 422,

  DBR_BANDS_INVALID: 422,
  DBR_BAND_CAP_OUT_OF_RANGE: 422,
  PROGRAM_RANGE_INVALID: 422,
  PROGRAM_NAME_KEY_UNKNOWN: 422,
  PROGRAM_NAME_KEY_NOT_IN_CATEGORY: 422,
  ANSWER_TYPE_MISMATCH: 400,
  ANSWER_OUT_OF_RANGE: 400,
  ANSWER_TOO_LONG: 400,
  ANSWER_REQUIRED: 400,
  QUESTION_TYPE_RULES_INVALID: 422,
  QUESTION_TYPE_NOT_SCOREABLE: 422,
  MONEY_FIELD_BINDING_MISSING: 422,
  MONEY_FIGURE_MISSING: 422,
  OBLIGATIONS_TOTAL_MISMATCH: 422,
  CALCULATOR_INPUT_INVALID: 400,
  CALCULATOR_PROGRAM_INACTIVE: 409,
  PROGRAM_MISCONFIGURED: 422,
  // Reason codes + disclaimer: only ever returned inside a 200 payload.
  NO_RECOGNISED_INCOME: 200,
  OBLIGATIONS_EXCEED_ALLOWANCE: 200,
  BELOW_PROGRAM_MIN_AMOUNT: 200,
  AGE_AT_MATURITY: 200,
  CURRENCY_NOT_OFFERED: 200,
  INDICATIVE_ESTIMATE_NOT_AN_OFFER: 200,

  INCOME_RULE_EMPTY: 422,
  INCOME_RULE_INCOME_INVALID: 422,
  INCOME_RULE_DUPLICATE_KEY: 422,
  INCOME_RULE_UNKNOWN_KEY: 422,
  INCOME_RULE_BANDS_INVALID: 422,
  INCOME_RULE_DBR_OVERRIDE_INVALID: 422,
  VALUE_SOURCE_PATH_UNKNOWN: 422,
  VALUE_SOURCE_VALUE_INVALID: 422,
  PROGRAM_HAS_ESTIMATED_VALUES: 409,
  SURROGATE_FACT_BINDING_MISSING: 422,
  // Reason codes: only ever returned inside a 200 payload.
  SURROGATE_FACT_MISSING: 200,
  SURROGATE_NO_MATCHING_ROW: 200,

  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
};

export const ALL_ERROR_CODES: readonly ErrorCode[] = Object.values(ERROR_CODES);
