import type { SeedCatalog } from '../catalog.types';
import { skeletonProgram } from './base';

/**
 * Sales-floor catalog from operator notes (spec.md Appendix).
 * 4 products. SF-AUTO carries the derivation chain on the 4M-asset-value band.
 */
export const salesfloorEgp2026: SeedCatalog = {
  name: 'salesfloor-egp-2026',
  programs: [
    skeletonProgram({
      programCode: 'SF-BLUE-PLUS',
      bankName: 'Sales Floor (2026)',
      friendlyName: 'Blue / Plus — no-docs',
      programNameKey: 'private_sector',
      programType: 'income_surrogate',
      productCategory: 'personal',
      tenor: { minMonths: 12, maxMonths: 84 },
      loanLimits: { perCurrency: { EGP: { minAmount: '20000', maxAmount: '760000' } } },
      pricing: { isVariableRate: false, baseRatePercent: '27.0000' },
      eligibility: {
        acceptedEmploymentTypes: ['salaried', 'self_employed'],
        ageMin: 21,
        ageMax: 60,
        minMonthlyIncomeEGP: '0',
        minMonthsInJob: 0,
        dbrCapPercent: '50.0000',
        skipDbrCheck: false,
        acceptedTransferTypes: [
          'payroll',
          'salary_transfer_letter',
          'income_transfer_letter',
          'none',
        ],
        requiresCD: false,
        requiresAutoLoanAtABK: false,
        requiresAutoLoanAtOtherBank: false,
        requiresCreditCardAtOtherBank: false,
        requiresCompoundProperty: false,
        requiresCollateral: false,
        requiresClubMembership: false,
        requiresExistingLoan: false,
        requiresFRMUVerification: false,
        requiresQualitativeReview: false,
        requiresNoDocuments: true,
      },
      incomeAssumption: { strategy: 'declared' },
      fees: feesAt('2.5000'),
      operatorTips: ['Can be promoted on our pages — TikTok, Instagram, Facebook.'],
    }),
    skeletonProgram({
      programCode: 'SF-SELF-EMP',
      bankName: 'Sales Floor (2026)',
      friendlyName: 'Self-Employed / Business Owner',
      programNameKey: 'professional',
      programType: 'income_proof',
      productCategory: 'personal',
      tenor: { minMonths: 12, maxMonths: 84 },
      loanLimits: {
        perCurrency: { EGP: { minAmount: '100000', maxAmount: '2000000' } },
        qualitativeReviewMaxEGP: '3000000',
      },
      pricing: {
        isVariableRate: false,
        baseRatePercent: '29.0000',
        rateByLoanAmountBand: {
          '0': { value: '29.0000' },
          '1000001': { value: '28.0000' },
        },
      },
      eligibility: {
        acceptedEmploymentTypes: ['self_employed'],
        ageMin: 25,
        ageMax: 60,
        minMonthlyIncomeEGP: '10000',
        minMonthsInJob: 24,
        dbrCapPercent: '50.0000',
        skipDbrCheck: false,
        acceptedTransferTypes: ['none'],
        requiresCD: false,
        requiresAutoLoanAtABK: false,
        requiresAutoLoanAtOtherBank: false,
        requiresCreditCardAtOtherBank: false,
        requiresCompoundProperty: false,
        requiresCollateral: false,
        requiresClubMembership: false,
        requiresExistingLoan: false,
        requiresFRMUVerification: false,
        requiresQualitativeReview: true,
        requiresNoDocuments: false,
      },
      incomeAssumption: { strategy: 'byBankStatementPercent', bankStatementPercent: '30.0' },
      fees: feesAt('2.5000'),
    }),
    skeletonProgram({
      programCode: 'SF-HIGH-END',
      bankName: 'Sales Floor (2026)',
      friendlyName: 'High End — Wealth Tier',
      programNameKey: 'professional',
      programType: 'income_proof',
      productCategory: 'wealth',
      tenor: { minMonths: 12, maxMonths: 60 },
      loanLimits: { perCurrency: { EGP: { minAmount: '1000000', maxAmount: '10000000' } } },
      pricing: { isVariableRate: false, baseRatePercent: '28.0000' },
      eligibility: {
        acceptedEmploymentTypes: ['salaried', 'self_employed'],
        ageMin: 30,
        ageMax: 65,
        minMonthlyIncomeEGP: '50000',
        minMonthsInJob: 36,
        dbrCapPercent: '50.0000',
        skipDbrCheck: false,
        acceptedTransferTypes: ['none'],
        requiresCD: false,
        requiresAutoLoanAtABK: false,
        requiresAutoLoanAtOtherBank: false,
        requiresCreditCardAtOtherBank: false,
        requiresCompoundProperty: false,
        requiresCollateral: false,
        requiresClubMembership: false,
        requiresExistingLoan: false,
        requiresFRMUVerification: false,
        requiresQualitativeReview: true,
        requiresNoDocuments: false,
        minBankStatementBalanceEGP: '100000000',
        minAssetsValueEGP: '7000000',
      },
      incomeAssumption: { strategy: 'declared' },
      fees: feesAt('0.0000'),
    }),
    skeletonProgram({
      programCode: 'SF-AUTO',
      bankName: 'Sales Floor (2026)',
      friendlyName: 'Auto Loan — Down-Payment Tiered',
      programNameKey: 'new_car',
      programType: 'income_proof',
      productCategory: 'car',
      tenor: { minMonths: 12, maxMonths: 84 },
      loanLimits: { perCurrency: { EGP: { minAmount: '100000', maxAmount: '5000000' } } },
      pricing: {
        isVariableRate: false,
        baseRatePercent: '26.0000',
        rateByDownPaymentPercent: {
          '30': { value: '25.5000' },
          '40': { value: '23.5000' },
          '45': { value: '22.5000' },
          '50': { value: '22.2500' },
          '60': { value: '21.7500' },
        },
        rateByAssetValueBand: {
          // Above 4M car price → −1% from the cascade-selected rate.
          // FR-008p mandates absolute values; we capture the derivation on each band.
          '4000001': {
            value: '24.5000',
            derivation: {
              sourceRatePercent: '25.5000',
              deltaPercent: '-1.0000',
              reason: 'car price exceeds 4M threshold',
            },
          },
        },
        feeWaiverPenaltyRatePercent: '2.0000',
        feeWaiverPenaltyMinTenorMonths: 36,
        insuranceWaiverPenaltyRatePercent: '2.0000',
        insuranceWaiverPenaltyMinTenorMonths: 36,
      },
      eligibility: {
        acceptedEmploymentTypes: ['salaried', 'self_employed'],
        ageMin: 21,
        ageMax: 65,
        minMonthlyIncomeEGP: '10000',
        minMonthsInJob: 6,
        dbrCapPercent: '50.0000',
        skipDbrCheck: false,
        acceptedTransferTypes: [
          'payroll',
          'salary_transfer_letter',
          'income_transfer_letter',
          'none',
        ],
        requiresCD: false,
        requiresAutoLoanAtABK: false,
        requiresAutoLoanAtOtherBank: false,
        requiresCreditCardAtOtherBank: false,
        requiresCompoundProperty: false,
        requiresCollateral: false,
        requiresClubMembership: false,
        requiresExistingLoan: false,
        requiresFRMUVerification: false,
        requiresQualitativeReview: false,
        requiresNoDocuments: false,
        eligibleDownPaymentPercent: '30.0000',
      },
      incomeAssumption: { strategy: 'declared' },
      fees: feesAt('2.5000'),
    }),
  ],
  expectedRates: {
    'SF-BLUE-PLUS': '27.0000',
    'SF-SELF-EMP': '29.0000',
    'SF-HIGH-END': '28.0000',
    'SF-AUTO': '26.0000',
  },
};

function feesAt(adminFee: string) {
  return {
    adminFeePercent: adminFee,
    stampDutyPercent: '0.5000',
    lifeInsurancePercent: '0.5000',
    lifeInsuranceMandatory: false,
    latePaymentFeePercent: '4.0000',
    payoffCashPercent: '12.0000',
    payoffBuyoutPercent: '15.0000',
  };
}
