/**
 * FR-037 — the ONE-OFF review of programs that predate value-source marking.
 *
 * Every program created before this feature carries `valueSources = {}`, which reads
 * as "the bank stated every number on this program". That is what keeps them LIVE on
 * deploy (a backfill marking them estimated would take the whole book off air), and it
 * is also why they need a deliberate pass: an empty map is not a confirmation, it is
 * the absence of a question — and they never appear on the waiting list, so nothing
 * will ever prompt anyone to look at them.
 *
 * This script produces that prompt, once, as a checklist on disk.
 *
 *   npx tsx scripts/pre-existing-programs-review.ts
 *
 * Read-only: it writes a markdown file and touches no database row.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { PrismaClient } from '@prisma/client';
import { markablePaths } from '../src/bank-programs/validation/value-sources.validator';

const OUT = resolve(__dirname, '../../specs/011-surrogate-admin-panel/pre-existing-programs-review.md');

async function main(): Promise<void> {
  const prisma = new PrismaClient();
  try {
    const programs = await prisma.bankProgram.findMany({
      orderBy: [{ bankName: 'asc' }, { programCode: 'asc' }],
    });

    const rows = programs
      .map((p) => {
        const sources = (p.valueSources ?? {}) as Record<string, unknown>;
        const numeric = markablePaths({
          incomeAssumption: p.incomeAssumption,
          pricing: p.pricing,
          fees: p.fees,
          loanLimits: p.loanLimits,
          tenor: p.tenor,
          eligibility: p.eligibility,
          performanceCriteria: p.performanceCriteria,
        });
        return {
          programCode: p.programCode,
          bankName: p.bankName,
          friendlyName: p.friendlyName,
          active: p.active,
          numericFieldCount: numeric.size,
          alreadyMarked: Object.keys(sources).length > 0,
        };
      })
      // The review set: an EMPTY map and at least one number to be wrong about. A
      // program already carrying markers is on the waiting list and needs no prompt;
      // one with no numeric fields at all has nothing to confirm.
      .filter((r) => !r.alreadyMarked && r.numericFieldCount > 0);

    const live = rows.filter((r) => r.active).length;
    const lines = [
      '# Pre-existing programs — one-off source review (FR-037)',
      '',
      'Generated by `backend/scripts/pre-existing-programs-review.ts`. Read-only.',
      '',
      '## Why this list exists',
      '',
      'Every program below predates value-source marking, so its marker map is empty.',
      'An empty map means "the bank stated every number here" — which is what keeps these',
      'programs LIVE on deploy rather than switching the whole book off. But an empty map',
      'is the ABSENCE of a question, not an answer to it, and because these programs never',
      'appear on the "Waiting for the bank" list, nothing will ever prompt anyone to check',
      'them. This file is that prompt, and it is meant to be walked once and then deleted.',
      '',
      '## What to do with each row',
      '',
      'Open the program, look at the numbers, and mark the ones nobody has confirmed with',
      'the bank as **We estimated this**. Marking a number on a LIVE program switches that',
      'program off in the same save (FR-035) — that is intended, and it is the point: a',
      'guess that is live is the state this feature exists to end.',
      '',
      `**${rows.length} programs to review** (${live} currently live).`,
      '',
      '| ☐ | Program | Bank | Name | Live | Numbers to check |',
      '|---|---------|------|------|------|------------------|',
      ...rows.map(
        (r) =>
          `| ☐ | \`${r.programCode}\` | ${r.bankName} | ${r.friendlyName} | ${r.active ? 'yes' : 'no'} | ${r.numericFieldCount} |`,
      ),
      '',
      '---',
      '',
      'A program with markers already set is deliberately absent: it is on the waiting',
      'list, which is the live version of this question.',
      '',
    ];

    writeFileSync(OUT, `${lines.join('\n')}\n`, 'utf8');
    console.log(`wrote ${rows.length} programs (${live} live) → ${OUT}`);
  } finally {
    await prisma.$disconnect();
  }
}

void main();
