/**
 * Local mirror of the Prisma `AuditEventType` enum.
 *
 * Constitution Principle X / Clean Code Structure: only repositories import
 * from `@prisma/client`. Services, controllers, DTOs, and cross-feature code
 * use this local enum instead. Every member here MUST match the corresponding
 * value in `prisma/schema.prisma` exactly (same string), so no runtime
 * mapping is needed — the repository casts at its Prisma boundary.
 *
 * Anti-Pattern reference: A8 (controllers leaking `@prisma/client`) and the
 * "no magic strings" rule for audit-event types in NestJS Clean Code Structure
 * v2.0.0.
 */
export enum AuditEventType {
  // Admin auth events
  AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_TOKEN_REFRESHED = 'AUTH_TOKEN_REFRESHED',
  AUTH_PASSWORD_CHANGED = 'AUTH_PASSWORD_CHANGED',
  AUTH_PASSWORD_FORCED_CHANGE_COMPLETED = 'AUTH_PASSWORD_FORCED_CHANGE_COMPLETED',

  // Admin user management
  ADMIN_USER_CREATED = 'ADMIN_USER_CREATED',
  ADMIN_USER_UPDATED = 'ADMIN_USER_UPDATED',
  ADMIN_USER_DEACTIVATED = 'ADMIN_USER_DEACTIVATED',
  ADMIN_USER_ROLE_CHANGED = 'ADMIN_USER_ROLE_CHANGED',
  ADMIN_USER_PASSWORD_RESET = 'ADMIN_USER_PASSWORD_RESET',

  // Bank program lifecycle
  BANK_PROGRAM_CREATED = 'BANK_PROGRAM_CREATED',
  BANK_PROGRAM_UPDATED = 'BANK_PROGRAM_UPDATED',
  BANK_PROGRAM_TOGGLED = 'BANK_PROGRAM_TOGGLED',
  BANK_PROGRAM_DELETED = 'BANK_PROGRAM_DELETED',
  BANK_PROGRAM_RATE_UPDATED = 'BANK_PROGRAM_RATE_UPDATED',
  /**
   * Feature 011 / FR-038 — a value-source marker was added or removed, with the
   * editor's identity. Append-only history (Principle VI), read by nothing at
   * request time: "who called this number a guess, and when" has to stay answerable
   * after the fact, and only an event answers it.
   */
  BANK_PROGRAM_VALUE_SOURCE_CHANGED = 'BANK_PROGRAM_VALUE_SOURCE_CHANGED',
  /**
   * Feature 011 / FR-035 — a save introduced a team-estimated number on a LIVE
   * program, and the program was switched off in the SAME transaction. Recorded
   * separately from the ordinary toggle so "why did this go dark?" has an answer that
   * names the paths and the editor, rather than looking like someone flipped a switch.
   */
  BANK_PROGRAM_DEACTIVATED_BY_ESTIMATE = 'BANK_PROGRAM_DEACTIVATED_BY_ESTIMATE',
  BANK_PROGRAM_QUALITATIVE_REVIEW_DECIDED = 'BANK_PROGRAM_QUALITATIVE_REVIEW_DECIDED',

  // Banks (entity, not programs)
  BANK_CREATED = 'BANK_CREATED',
  BANK_UPDATED = 'BANK_UPDATED',
  BANK_TOGGLED = 'BANK_TOGGLED',
  BANK_DELETED = 'BANK_DELETED',
  BANK_LOGO_UPLOADED = 'BANK_LOGO_UPLOADED',

  // Application lifecycle (mobile + admin)
  APPLICATION_CREATED = 'APPLICATION_CREATED',
  APPLICATION_MATCHED = 'APPLICATION_MATCHED',
  APPLICATION_NO_MATCH = 'APPLICATION_NO_MATCH',
  APPLICATION_RATE_LIMITED = 'APPLICATION_RATE_LIMITED',
  MATCHING_ENGINE_RUN = 'MATCHING_ENGINE_RUN',
  DATA_ERASURE_COMPLETED = 'DATA_ERASURE_COMPLETED',
  SCORING_ENGINE_VERSION_PROMOTED = 'SCORING_ENGINE_VERSION_PROMOTED',
  APPLICATION_ACTIVITY_LOGGED = 'APPLICATION_ACTIVITY_LOGGED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  APPLICATION_REASSIGNED = 'APPLICATION_REASSIGNED',
  MANAGER_ATTENTION_REQUESTED = 'MANAGER_ATTENTION_REQUESTED',
  APPLICATION_LEAD_STATUS_CHANGED = 'APPLICATION_LEAD_STATUS_CHANGED',
  APPLICATION_USER_PROCEEDED = 'APPLICATION_USER_PROCEEDED',

  // Platform enumerations admin
  PLATFORM_ENUMERATION_CREATED = 'PLATFORM_ENUMERATION_CREATED',
  PLATFORM_ENUMERATION_UPDATED = 'PLATFORM_ENUMERATION_UPDATED',
  PLATFORM_ENUMERATION_DEACTIVATED = 'PLATFORM_ENUMERATION_DEACTIVATED',
  PLATFORM_ENUMERATION_DEPRECATED = 'PLATFORM_ENUMERATION_DEPRECATED',
  PLATFORM_ENUMERATION_DELETED = 'PLATFORM_ENUMERATION_DELETED',
  /** The KIND of list itself (`enumeration_type_def`), not a value inside one. */
  ENUMERATION_TYPE_CREATED = 'ENUMERATION_TYPE_CREATED',
  ENUMERATION_TYPE_UPDATED = 'ENUMERATION_TYPE_UPDATED',
  ENUMERATION_TYPE_DELETED = 'ENUMERATION_TYPE_DELETED',

  // Customer (mobile) auth — legacy v1.7.0 model
  CUSTOMER_SIGNED_UP = 'CUSTOMER_SIGNED_UP',
  CUSTOMER_LOGGED_IN = 'CUSTOMER_LOGGED_IN',
  CUSTOMER_LOGGED_OUT = 'CUSTOMER_LOGGED_OUT',
  CUSTOMER_TOKEN_REFRESHED = 'CUSTOMER_TOKEN_REFRESHED',
  CUSTOMER_PASSWORD_CHANGED = 'CUSTOMER_PASSWORD_CHANGED',
  // Admin revealed a customer PII document binary (National ID). Principle VI.
  CUSTOMER_DOCUMENT_REVEALED = 'CUSTOMER_DOCUMENT_REVEALED',

  // Support
  SUPPORT_REQUEST_CREATED = 'SUPPORT_REQUEST_CREATED',
  SUPPORT_REQUEST_ASSIGNED = 'SUPPORT_REQUEST_ASSIGNED',
  SUPPORT_REQUEST_RESOLVED = 'SUPPORT_REQUEST_RESOLVED',
  SUPPORT_CONFIG_UPDATED = 'SUPPORT_CONFIG_UPDATED',

  // Onboarding screens
  ONBOARDING_SCREEN_CREATED = 'ONBOARDING_SCREEN_CREATED',
  ONBOARDING_SCREEN_UPDATED = 'ONBOARDING_SCREEN_UPDATED',
  ONBOARDING_SCREEN_DELETED = 'ONBOARDING_SCREEN_DELETED',
  ONBOARDING_SCREEN_REORDERED = 'ONBOARDING_SCREEN_REORDERED',

  // Funnel telemetry (mobile)
  CATALOG_VIEWED = 'CATALOG_VIEWED',
  QUESTIONNAIRE_STARTED = 'QUESTIONNAIRE_STARTED',
  OFFERS_VIEWED = 'OFFERS_VIEWED',

  // Feature 008 — Constitution v1.8.0 two-path registration
  CUSTOMER_OTP_REQUESTED = 'CUSTOMER_OTP_REQUESTED',
  CUSTOMER_OTP_VERIFIED = 'CUSTOMER_OTP_VERIFIED',
  CUSTOMER_OTP_FAILED = 'CUSTOMER_OTP_FAILED',
  CUSTOMER_SIGNUP_PHONE_COMPLETED = 'CUSTOMER_SIGNUP_PHONE_COMPLETED',
  CUSTOMER_SIGNUP_SOCIAL_COMPLETED = 'CUSTOMER_SIGNUP_SOCIAL_COMPLETED',
  CUSTOMER_PROFILE_MOBILE_BOUND = 'CUSTOMER_PROFILE_MOBILE_BOUND',
  CUSTOMER_PROFILE_COMPLETED = 'CUSTOMER_PROFILE_COMPLETED',
  CUSTOMER_PROFILE_UPDATED = 'CUSTOMER_PROFILE_UPDATED',
  CUSTOMER_PROFILE_EMAIL_SET = 'CUSTOMER_PROFILE_EMAIL_SET',
  CUSTOMER_PROFILE_AGE_SET = 'CUSTOMER_PROFILE_AGE_SET',
  CUSTOMER_LOGIN_FAILED = 'CUSTOMER_LOGIN_FAILED',
  CUSTOMER_LOGIN_LOCKED = 'CUSTOMER_LOGIN_LOCKED',
  CUSTOMER_TOKENS_REVOKED_OTHERS = 'CUSTOMER_TOKENS_REVOKED_OTHERS',
  CUSTOMER_PASSWORD_RESET = 'CUSTOMER_PASSWORD_RESET',
  APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',

  // Admin-initiated customer account status (super_admin only)
  CUSTOMER_DEACTIVATED = 'CUSTOMER_DEACTIVATED',
  CUSTOMER_REACTIVATED = 'CUSTOMER_REACTIVATED',

  // Feature 00X — questionnaire + scoring weights (v5.0.0: direct save)
  QUESTIONNAIRE_PUBLISHED = 'QUESTIONNAIRE_PUBLISHED',
  SCORING_WEIGHTS_SAVED = 'SCORING_WEIGHTS_SAVED',

  // RETIRED with the removal of prefill / catalog defaults — no writer remains.
  // The values are preserved (not dropped) because `audit_event` rows are
  // append-only (Principle VI) and a Postgres enum value cannot be removed in
  // place without recreating `AuditEventType`. Do not emit these.
  BANK_POLICY_UPDATED = 'BANK_POLICY_UPDATED',
  PROGRAM_CATALOG_DEFAULTS_UPDATED = 'PROGRAM_CATALOG_DEFAULTS_UPDATED',
}
