-- The two Suez Canal auto products become ONE product with two ways.
--
-- WHY. `down_payment_income` (income = the car down payment ÷ 3.6) and `savings_income`
-- (income = demonstrated savings ÷ 3.6 for an instalment buyer, ÷ 12 for a cash one) shipped
-- as two products on 2026-09-08. Same arithmetic, same bank, same loan type; the operator asked
-- why a bank program could not simply pick which of the two it sells, the way a compound program
-- picks one of five derivations — and decided (2026-09-09) that it should.
--
-- WHAT KEPT THEM APART, AND WHAT CHANGED. A second column lived on the PRODUCT and reached every
-- way: merged, the savings split (instalment / cash) would have landed on the down-payment way
-- too, five programmes would have been asked for a divisor their sheet does not print, and a
-- blank cash column still counts a way as filled — so a cash buyer would have been quoted
-- NOTHING by those five, silently. `TemplateMechanism.column` now puts a column on ONE way, and
-- this file moves the data to match.
--
-- WHY A MIGRATION AND NOT THE SEED. `npm run seed:blueprints` never touches a product that
-- already holds a calculation (`planSeedAction` answers `skip`), so the merged blueprint would
-- never reach an already-seeded row; `seed:sheet-figures` skips a product that already holds
-- figures for the same reason. Both halves of this — the product's shape and the two Green
-- programmes' figures — live in Postgres and are only correct together, so they move together.
-- A fresh database is seeded straight into the merged state and this file finds nothing to do.
--
-- THE SHAPE IS WRITTEN HERE, NOT LEFT TO A SEED. The alternative — data moves here, recompile
-- later with `blueprint:retemplate` — leaves a window in which the two Green programmes name a
-- way (`alt`) their product does not yet have and quote nothing. `templateSpec` below is the
-- merged blueprint's form verbatim and `incomeRule` is `compileTemplate` of it, generated by the
-- compiler and pasted; `seed:sheet-figures` re-run afterwards reporting the two programmes
-- "identical to what is stored" and `blueprint:retemplate down_payment_income` (dry run) reporting
-- nothing to drop and nothing to retire are the proofs this wrote exactly what the code would.
--
-- WHICH KEY SURVIVES. `down_payment_income`: five programmes already file their figures under
-- its `primary` slot, and a key is what `platform_enumeration.surrogateProductKey`,
-- `surrogate_product_ask.productId` and the blueprint registry all address. The savings way
-- becomes `alt` — the slot the compiler gives a second way — with its cash column at
-- `alt__cash_buyer` and its pick at `alt_pick`. The two Green programmes' figures are RENAMED
-- from `primary` / `primary__cash_buyer` to those ids and their `wayId` from `primary` to `alt`.
--
-- NO FIGURE MOVES, and it is checked in both directions: every stored divisor is carried
-- (renamed, never retyped — the savings product's own defaults become the merged product's
-- `alt` defaults), the five down-payment programmes are not touched at all, and the DO block
-- RAISEs rather than commits if anything under either product holds a figure this file does not
-- know how to move.

DO $$
DECLARE
  dp        "platform_enumeration"%ROWTYPE;
  sv        "platform_enumeration"%ROWTYPE;
  sv_params jsonb;
  bad       int;
  n         int;
  merged_template jsonb := '{"version":1,"blueprintKey":"down_payment_income","outputKind":"monthlyIncome","iScore":true,"primary":{"kind":"dividedBy","fact":"car_down_payment"},"alternatives":[{"kind":"dividedBy","fact":"total_savings","column":{"fact":"green_buyer_type","branches":["instalment_buyer","cash_buyer"]}}],"waysAre":"exclusive","conditions":[]}'::jsonb;
  merged_shape    jsonb := '{"strategy":"steps","waysAre":"exclusive","steps":[{"id":"src__car_down_payment","op":"factNumber","fact":"car_down_payment"},{"id":"src__total_savings","op":"factNumber","fact":"total_savings"},{"id":"primary","op":"divide","of":{"step":"src__car_down_payment"}},{"id":"alt","op":"divide","of":{"step":"src__total_savings"}},{"id":"alt__cash_buyer","op":"divide","of":{"step":"src__total_savings"}},{"id":"alt_pick","op":"pickByFact","fact":"green_buyer_type","of":[{"step":"alt"},{"step":"alt__cash_buyer"}],"branches":["instalment_buyer","cash_buyer"]},{"id":"basis","op":"coalesce","of":[{"step":"primary"},{"step":"alt_pick"}]},{"id":"iscore_src","op":"factNumber","fact":"i_score","optional":true},{"id":"iscore_band","op":"bandTable","of":{"step":"iscore_src"}},{"id":"iscore_factor","op":"coalesce","of":[{"step":"iscore_band"},{"const":"100"}]},{"id":"iscore_applied","op":"percentOf","of":[{"step":"basis"},{"step":"iscore_factor"}]}],"gates":[],"output":{"kind":"monthlyIncome","from":"iscore_applied"}}'::jsonb;
BEGIN
  SELECT * INTO sv FROM "platform_enumeration" WHERE "type" = 'surrogate_product' AND "key" = 'savings_income';
  IF NOT FOUND THEN
    RAISE NOTICE 'auto_product_one_two_ways: no savings_income product — nothing to merge (fresh database, or already merged)';
    RETURN;
  END IF;

  SELECT * INTO dp FROM "platform_enumeration" WHERE "type" = 'surrogate_product' AND "key" = 'down_payment_income';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'auto_product_one_two_ways: savings_income exists but down_payment_income does not — nothing to merge INTO';
  END IF;

  -- 0. Guards: the two rows must be in the shape the seed left them, or this file does not
  --    know what it is moving.
  IF EXISTS (SELECT 1 FROM jsonb_array_elements(dp."incomeRule" -> 'steps') s WHERE s ->> 'id' = 'alt') THEN
    RAISE EXCEPTION 'auto_product_one_two_ways: down_payment_income already carries an alt way';
  END IF;
  sv_params := COALESCE(sv."incomeRule" -> 'stepParams', '{}'::jsonb);
  SELECT count(*) INTO bad FROM jsonb_object_keys(sv_params) k
    WHERE k NOT IN ('primary', 'primary__cash_buyer', 'iscore_band');
  IF bad > 0 THEN
    RAISE EXCEPTION 'auto_product_one_two_ways: savings_income holds % catalog figure(s) under keys this file cannot place', bad;
  END IF;
  SELECT count(*) INTO bad FROM jsonb_object_keys(COALESCE(dp."incomeRule" -> 'stepParams', '{}'::jsonb)) k
    WHERE k NOT IN ('primary', 'iscore_band');
  IF bad > 0 THEN
    RAISE EXCEPTION 'auto_product_one_two_ways: down_payment_income holds % catalog figure(s) under unexpected keys', bad;
  END IF;
  -- Every programme under a name that sells the savings product must hold only the two slots
  -- this file renames, and sell the one way there was.
  SELECT count(*) INTO bad
  FROM "bank_program" bp
  JOIN "platform_enumeration" nm ON nm."type" = 'program_name' AND nm."key" = bp."programNameKey"
  WHERE nm."surrogateProductKey" = 'savings_income'
    AND (
      COALESCE(bp."incomeAssumption" ->> 'wayId', 'primary') <> 'primary'
      OR EXISTS (
        SELECT 1 FROM jsonb_object_keys(COALESCE(bp."incomeAssumption" -> 'stepParams', '{}'::jsonb)) k
        WHERE k NOT IN ('primary', 'primary__cash_buyer')
      )
    );
  IF bad > 0 THEN
    RAISE EXCEPTION 'auto_product_one_two_ways: % programme(s) on the savings product hold figures or a way this file cannot move', bad;
  END IF;

  -- 1. The Green programmes: the same figures, filed under the savings WAY of the one product.
  --    Renamed by key, never retyped — a bank that changed a divisor keeps its own number.
  UPDATE "bank_program" bp
  SET "incomeAssumption" =
        (bp."incomeAssumption" - 'stepParams')
        || jsonb_build_object('wayId', 'alt')
        || jsonb_build_object(
             'stepParams',
             (COALESCE(bp."incomeAssumption" -> 'stepParams', '{}'::jsonb) - 'primary' - 'primary__cash_buyer')
             || CASE WHEN bp."incomeAssumption" -> 'stepParams' ? 'primary'
                     THEN jsonb_build_object('alt', bp."incomeAssumption" -> 'stepParams' -> 'primary')
                     ELSE '{}'::jsonb END
             || CASE WHEN bp."incomeAssumption" -> 'stepParams' ? 'primary__cash_buyer'
                     THEN jsonb_build_object('alt__cash_buyer', bp."incomeAssumption" -> 'stepParams' -> 'primary__cash_buyer')
                     ELSE '{}'::jsonb END
           ),
      "updatedAt" = now()
  FROM "platform_enumeration" nm
  WHERE nm."type" = 'program_name'
    AND nm."key" = bp."programNameKey"
    AND nm."surrogateProductKey" = 'savings_income';
  GET DIAGNOSTICS n = ROW_COUNT;
  RAISE NOTICE 'auto_product_one_two_ways: % programme(s) moved onto the alt way', n;

  -- 2. What the savings product ASKS becomes what the merged product asks. Insert-only, then
  --    the rest go with the row (ON DELETE CASCADE) — but explicitly, so the count below is exact.
  INSERT INTO "surrogate_product_ask" ("productId", "factId", "source", "createdAt", "createdBy", "detachedAt", "detachedBy")
  SELECT dp."id", a."factId", a."source", a."createdAt", a."createdBy", a."detachedAt", a."detachedBy"
  FROM "surrogate_product_ask" a
  WHERE a."productId" = sv."id"
    AND NOT EXISTS (SELECT 1 FROM "surrogate_product_ask" d WHERE d."productId" = dp."id" AND d."factId" = a."factId");
  DELETE FROM "surrogate_product_ask" WHERE "productId" = sv."id";

  -- 3. Facts filed under the savings product (provenance only; none on the seeded database).
  UPDATE "platform_enumeration" SET "surrogateProductKey" = 'down_payment_income', "updatedAt" = now()
  WHERE "type" = 'surrogate_fact' AND "surrogateProductKey" = 'savings_income';

  -- 4. The Green catalog name sells the merged product.
  UPDATE "platform_enumeration" SET "surrogateProductKey" = 'down_payment_income', "updatedAt" = now()
  WHERE "type" = 'program_name' AND "surrogateProductKey" = 'savings_income';

  -- 5. The merged product: its form, its compiled shape, its defaults (own + the savings way's,
  --    renamed), and a label that names the applicant (car buyers) and both things they may show, on the same "Segment — qualifier" pattern as every other product card. Estimate markers are the I-Score tiers'
  --    on both rows and identical, so the merged row keeps its own.
  UPDATE "platform_enumeration"
  SET "templateSpec" = merged_template,
      "incomeRule" = merged_shape || jsonb_build_object(
        'stepParams',
        COALESCE(dp."incomeRule" -> 'stepParams', '{}'::jsonb)
        || CASE WHEN sv_params ? 'primary' THEN jsonb_build_object('alt', sv_params -> 'primary') ELSE '{}'::jsonb END
        || CASE WHEN sv_params ? 'primary__cash_buyer' THEN jsonb_build_object('alt__cash_buyer', sv_params -> 'primary__cash_buyer') ELSE '{}'::jsonb END
      ),
      "labelEn" = 'Car Buyers — Down Payment or Savings',
      "labelAr" = 'مشترو السيارات — الدفعة المقدمة أو المدخرات',
      "updatedAt" = now()
  WHERE "id" = dp."id";

  -- 6. The savings product row goes, after nothing points at it any more.
  IF EXISTS (SELECT 1 FROM "platform_enumeration" WHERE "surrogateProductKey" = 'savings_income') THEN
    RAISE EXCEPTION 'auto_product_one_two_ways: something still points at savings_income';
  END IF;
  DELETE FROM "platform_enumeration" WHERE "id" = sv."id";

  -- 7. The end state, asserted rather than assumed.
  IF NOT EXISTS (
    SELECT 1 FROM "platform_enumeration" p, jsonb_array_elements(p."incomeRule" -> 'steps') s
    WHERE p."id" = dp."id" AND s ->> 'id' = 'alt_pick'
  ) THEN
    RAISE EXCEPTION 'auto_product_one_two_ways: merged product carries no alt_pick step';
  END IF;
  SELECT count(*) INTO n FROM "platform_enumeration"
    WHERE "type" = 'program_name' AND "surrogateProductKey" = 'down_payment_income';
  IF n <> 2 THEN
    RAISE EXCEPTION 'auto_product_one_two_ways: expected 2 catalog names on the merged product, found %', n;
  END IF;
  SELECT count(*) INTO n FROM "surrogate_product_ask" WHERE "productId" = dp."id";
  IF n < 3 THEN
    RAISE EXCEPTION 'auto_product_one_two_ways: expected at least 3 asks on the merged product, found %', n;
  END IF;
  SELECT count(*) INTO bad
  FROM "bank_program" bp
  JOIN "platform_enumeration" nm ON nm."type" = 'program_name' AND nm."key" = bp."programNameKey"
  WHERE nm."surrogateProductKey" = 'down_payment_income'
    AND bp."incomeAssumption" ->> 'wayId' NOT IN ('primary', 'alt');
  IF bad > 0 THEN
    RAISE EXCEPTION 'auto_product_one_two_ways: % programme(s) on the merged product name no way', bad;
  END IF;
END $$;
